# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f659e65ed0ad2b10e54595f2225b7cc7aac29690bd8a28fc899ed72843c6325a480d7493c786547ee23b730826b1c6e1e5167c01233741c60b1486a385baaf

test:
  secret_key_base: 3df62fc2947c0e2912fbf6bd5b373ed9438f6176e6d7ee5059b0c274a4ac365d45ec0014cf5f6ffbfbdffa69c2a842563f0ae50f6f3c64cf6a9d7159ecd52a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
